### ISSUE TITLE
Changing fontSize / delete extension

### ISSUE THREAD

**Issue by Aejkatappaja** [blackmann/fonted#4]
Hello, 

Everything works well excepts i can't change fontSize, so i disabled and removed the extension, but the font in my explorer kept the `Fonted` modified one... 

How can i delete this please ? 

![Screenshot 2023-10-03 at 14 44 41](https://github.com/blackmann/fonted/assets/119339477/6cb3998f-dbb4-4690-b7f8-e9563fbf8e86)

**Comment by blackmann** [comment]
You need to reinstall Fonted, then run `Fonted: Disable` command (from the command palette <kbd>Cmd+Shift+P</kbd>). And then uninstall afterwards

**Comment by Aejkatappaja** [comment]
> Fonted: Disable

That doesn't work + i still have the "Your Code installation appears to be corrupt"message.

Isn't there any file to remove on my Library folder ?

**Comment by Aejkatappaja** [comment]
Finally that disappeared today 😀
