### ISSUE TITLE
Does this work with cursor

### ISSUE THREAD

**Issue by T04435** [blackmann/fonted#9]
I'm using Cursor and when using this all I get is the font changed to some Serif font.

Also unistalled it and the font still Serif everywhere.

**Comment by blackmann** [comment]
Yes, it works in Cursor. You have to make sure the font is installed on your system.

**Comment by cooldevdotcodes** [comment]
@T04435 You need to install fonted v0.07 to make it works. fonted v1.0.0 or later isn't compatible with current version of Cursor
